name: 'Post Slack Update'
description: 'Posts update messages to Slack'
inputs:
  channel-id:
    description: 'Slack Channel ID'
    required: false
    default: 'C03SCNJ5WCB'
  commit-author:
    description: 'Commit Author'
    required: true
  commit-message:
    description: 'Commit Message'
    required: true
  commit-id:
    description: 'Commit ID'
    required: true
  slack-bot-token:
    description: 'Slack Bot Token'
    required: true
  env-name:
    description: 'Environment Name'
    required: true
  job-status:
    description: 'Job Status'
    required: false
  update-slack:
    description: 'Update slack message'
    required: false
    default: 'false'
  message-ts:
    description: 'Timestamp of the original Slack message'
    required: false

runs:
  using: 'composite'
  steps:    
    - name: Post to Slack channel2222
      run: "echo 'Posting to Slack'"


