name: Call a reusable workflow

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
  call-workflow:
    uses: yamini-sethu/github-actions-course-template/.github/workflows/reusable-workflow.yml@master
    with:
      deployment_environment: dev      
    secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
