name: Call a reusable workflow

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
  set-env:
    environment: dev
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Retrieving commit details for Slack Notification
        id: commit-info
        run: |
          COMMIT_INFO=$(git log -1 --pretty=format:'{"commit_id": "%H", "author": "%an", "message": "%s"}')
          echo "COMMIT_ID=$(echo $COMMIT_INFO | jq -r '.commit_id')" >> $GITHUB_OUTPUT
          echo "AUTHOR=$(echo $COMMIT_INFO | jq -r '.author')" >> $GITHUB_OUTPUT 
          echo "COMMIT_MESSAGE=$(echo $COMMIT_INFO | jq -r '.message')" >> $GITHUB_OUTPUT

      - name: Post to Slack
        id: post_slack
        uses: ./.github/actions/post-slack-custom@master
        with:
          commit-author: ${{ steps.commit-info.outputs.commit-info.AUTHOR }}
          commit-message: ${{ steps.commit-info.outputs.commit-info.COMMIT_MESSAGE }}
          commit-id: ${{ steps.commit-info.outputs.commit-info.COMMIT_ID }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          env-name: 'dev'
          update-slack: 'false'



      
        
