name: Call a reusable workflow

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
  deploy:
    uses: yamini-sethu/github-actions-course-template/.github/workflows/reusable-workflow.yml@master
    with:
        env: dev      
    secrets: inherit
        
