name: Deploy Dev New

on:
  workflow_dispatch:


jobs:
  deploy:
    environment: dev
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - run: echo The PR was merged
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Retrieve Secret from AWS Secret Manager and Write to Env File
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secrets: |
              serverless
              backend_param_file
              param_file
              SECRET_ALIAS_1,param_file
              SECRET_ALIAS_2,backend_param_file
          parse-json-secrets: false
              

        id: getSecret
      - name: Decode and Write Env file 
        run: |  
          API_KEY=`aws secretsmanager get-secret-value --secret-id backend_param_file --region us-east-1 | jq --raw-output '.SecretString'| jq --raw-output '.prod_env_file'`
          echo "$API_KEY"
          echo "printing secret from ENV"
          echo "${{ env.backend_param_file }}"
          echo "${{ env.BACKEND_PARAM_FILE }}"
          echo "${{ env.SECRET_ALIAS_1 }}"
          echo "${{ env.SECRET_ALIAS_2 }}"
          echo "${{ env.serverless }}"
          echo "${{ env.SERVERLESS }}"
          echo "printing secret from output"
          echo "${{ steps.getSecret.outputs.serverless }}"
          echo "${{ steps.getSecret.outputs.SERVERLESS }}"
          echo "${{ steps.getSecret.outputs.backend_param_file }}"
          echo "${{ steps.getSecret.outputs.BACKEND_PARAM_FILE }}"
          echo "${{ steps.getSecret.outputs.SECRET_ALIAS_1 }}"
          echo "${{ steps.getSecret.outputs.SECRET_ALIAS_2 }}"
          echo "${{ steps.getSecret.outputs.serverless }}"
          echo "${{ steps.getSecret.outputs.SERVERLESS }}"
          echo "${{ env.backend_param_file }}"  | jq --raw-output '.SecretString'| jq --raw-output '.prod_env_file' | base64 --decode > param_file
          cat param_file
          echo "${{ steps.getSecret.outputs.backend_param_file }}"  | jq --raw-output '.SecretString'| jq --raw-output '.prod_env_file' | base64 --decode > PARAM_FILE1
          cat PARAM_FILE1
      


        
        

