name: Deploy Dev New

on:
  workflow_dispatch:


jobs:
  deploy:
    environment: dev
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - run: echo The PR was merged
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


      - name: Post to a Slack channel222
        id: slack7
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C03SCNJ5WCB'
          payload: |
            {
              "attachments": [
                {
                  "fallback": "TEST SBVT Backend Deployment",
                  "color": "good",
                  "pretext": "TEST SBVT Backend Deployment",
                  "fields": [
                    {
                      "title": "Author",
                      "value": "${{ env.AUTHOR }}",
                      "short": true
                    },
                    {
                      "title": "Environment",
                      "value": "dev",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "Running...",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ env.commit_id }}",
                      "short": true
                    },
                    {
                      "title": "Commit Message",
                      "value": "${{ env.commit_message }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          AUTHOR: yamini-sethu
          commit_id: 9a3c5a51ea35eb83cde19ec70f16c97bb1d54e38
          commit_message: SBVT-2396 contract change
        
        

