name: Deploy Dev New

on:
  workflow_dispatch:
    branches:
      - any

jobs:
  deploy:
    environment: dev
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - run: echo The PR was merged
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::791550794162:oidc-provider/token.actions.githubusercontent.com
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

